### ISSUE TITLE
IndexError: index 28 is out of bounds for axis 1 with size 28 while generating the decoys

### ISSUE THREAD

**Issue by krisphie** [fimrie/DeepCoy#6]
Hello!
I want to use DeepCoy for decoy generation based on 3172 active structures obtained by chembl. I successfully installed DeepCoy and generated output decoys for the P38-alpha_example from the jupyter notebook and for a small subset of my own actives (10 first ligands from my 3062 actives).

Nonetheless when I try to generate decoys for all 3062 of my own actives I get an Index error.
IndexError: index 28 is out of bounds for axis 1 with size 28
 

All my input files, commands and terminal output including the error are available at: https://box.fu-berlin.de/s/6WiPi8ejTkJpysD

I know that numpy starts counting at 0 and that 28 is out of the range of 0-27 but I do not know why this error occurs only in a larger subset as I do not see any differences in the file formats of the input files of the 10 or the 3062 ligands. I also ensured that both files  (.smi / .json) contain the same number of ligands (i.e. I ensured, that all molecules from the .smi could be red and processed by prepare_data.py to create the .json file. ).

 

I hope you can help me to solve the issue

**Comment by jpmfc6** [comment]
I also got the error: index 28 is out of bounds for axis 1 with size 28. I think it is caused by a size limit of the input molecules because when I removed the largest molecules from my input set, the scripts then ran successfully. I haven't figured out what part of the code specifies this, though.

**Comment by fimrie** [comment]
Apologies for the delay in responding to this issue.

This was indeed caused by a size limit for the molecules. The current version of DeepCoy only supports molecules up to 83 heavy atoms natively. I have updated the repo to check for this when preprocessing the molecules, but by default DeepCoy won't process/generate molecules larger than this. 

If you would like to generate decoys for larger molecules, you can do so by changing the `dataset_info` function in `utils.py` (from line 28). Assuming you're using `dataset="zinc"` (i.e. default settings), if you update Line 40 (shown below) and replace 84 with the size of the largest molecules you wish to consider +1 (i.e. 84 allows up to molecules with 83 atoms). 
`'bucket_sizes': np.array([28,31,33,35,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,53,55,58,84])`

Alternatively, you could define your own custom dataset within `dataset_info` and ensure molecules are preprocessed and generated using this.

As a word of caution, since the model was not trained or assessed on molecules this large, I am not 100% sure of the quality of the generated decoys for larger molecules, although the model should run.
